from django.utils.translation import gettext_lazy as _


AMERICAS_CHOICES = [
    # ── Priority ──────────────────────────────────────────
    ('USA', _('United States')),
    ('MEX', _('Mexico')),
    ('DOM', _('Dominican Republic')),
    ('CUB', _('Cuba')),
    ('VEN', _('Venezuela')),
    ('PRI', _('Puerto Rico')),
    ('PAN', _('Panama')),
    ('COL', _('Colombia')),
    ('NIC', _('Nicaragua')),
    ('HND', _('Honduras')),
    ('GTM', _('Guatemala')),
    ('SLV', _('El Salvador')),
    ('CRI', _('Costa Rica')),
    ('ARG', _('Argentina')),
    ('BRA', _('Brazil')),
    ('CAN', _('Canada')),
    ('ECU', _('Ecuador')),
    ('PER', _('Peru')),
    ('CHL', _('Chile')),
    ('BOL', _('Bolivia')),
    ('URY', _('Uruguay')),
    ('PRY', _('Paraguay')),
    ('JAM', _('Jamaica')),
    ('HTI', _('Haiti')),
    ('TTO', _('Trinidad and Tobago')),
    # ── Rest ──────────────────────────────────────────────
    ('AIA', _('Anguilla')),
    ('ATG', _('Antigua and Barbuda')),
    ('ABW', _('Aruba')),
    ('BRB', _('Barbados')),
    ('BLZ', _('Belize')),
    ('BMU', _('Bermuda')),
    ('BES', _('Bonaire, Sint Eustatius and Saba')),
    ('CYM', _('Cayman Islands')),
    ('CUW', _('Curaçao')),
    ('DMA', _('Dominica')),
    ('FLK', _('Falkland Islands')),
    ('GUF', _('French Guiana')),
    ('GRL', _('Greenland')),
    ('GRD', _('Grenada')),
    ('GLP', _('Guadeloupe')),
    ('GUY', _('Guyana')),
    ('MTQ', _('Martinique')),
    ('MSR', _('Montserrat')),
    ('KNA', _('Saint Kitts and Nevis')),
    ('LCA', _('Saint Lucia')),
    ('SPM', _('Saint Pierre and Miquelon')),
    ('VCT', _('Saint Vincent and the Grenadines')),
    ('BLM', _('Saint-Barthelemy')),
    ('MAF', _('Saint-Martin (French part)')),
    ('SXM', _('Sint Maarten (Dutch part)')),
    ('SGS', _('South Georgia')),
    ('SUR', _('Suriname')),
    ('BHS', _('The Bahamas')),
    ('TCA', _('Turks and Caicos Islands')),
    ('UMI', _('United States Minor Outlying Islands')),
    ('VGB', _('Virgin Islands (British)')),
    ('VIR', _('Virgin Islands (US)')),
    ('OTR', _('Other')),
]
