# Generated by Django 5.2.12 on 2026-04-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company name')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Website / Social media')),
                ('interest_teams', models.BooleanField(default=False, verbose_name='Estado 33 Teams')),
                ('interest_players', models.BooleanField(default=False, verbose_name='Player Sponsorships')),
                ('interest_showcases', models.BooleanField(default=False, verbose_name='Showcases / Tryouts')),
                ('interest_tournaments', models.BooleanField(default=False, verbose_name='Mexico Tournaments')),
                ('interest_full_program', models.BooleanField(default=False, verbose_name='Full Program Partnership')),
                ('budget', models.CharField(blank=True, choices=[('lt2500', 'Under $2,500'), ('2500_5k', '$2,500–$5,000'), ('5k_10k', '$5,000–$10,000'), ('gt10k', '$10,000+')], max_length=10, verbose_name='Estimated budget')),
                ('goal_brand_awareness', models.BooleanField(default=False, verbose_name='Brand Awareness')),
                ('goal_youth_athletes', models.BooleanField(default=False, verbose_name='Support Youth Athletes')),
                ('goal_community', models.BooleanField(default=False, verbose_name='Community Impact')),
                ('goal_marketing', models.BooleanField(default=False, verbose_name='Marketing / Exposure')),
                ('goal_international', models.BooleanField(default=False, verbose_name='International (U.S.–Mexico) Reach')),
                ('activation_logo', models.BooleanField(default=False, verbose_name='Logo on uniforms')),
                ('activation_event', models.BooleanField(default=False, verbose_name='Event branding')),
                ('activation_social', models.BooleanField(default=False, verbose_name='Social media promotion')),
                ('activation_onsite', models.BooleanField(default=False, verbose_name='On-site presence')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/logos/', verbose_name='Logo')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Ideas')),
                ('wants_proposal', models.BooleanField(default=False, verbose_name='Wants custom proposal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Submitted')),
            ],
            options={
                'verbose_name': 'Sponsor Inquiry',
                'verbose_name_plural': 'Sponsor Inquiries',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
