# Generated by Django 5.2.12 on 2026-04-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_sponsor_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('path', models.CharField(max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('is_mobile', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='landing_pag_timesta_1efd23_idx'), models.Index(fields=['country_code'], name='landing_pag_country_c897d0_idx'), models.Index(fields=['ip'], name='landing_pag_ip_5fd88e_idx')],
            },
        ),
    ]
