# Generated by Django 5.2.13 on 2026-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_page_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='device_type',
            field=models.CharField(default='desktop', max_length=10),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['device_type'], name='landing_pag_device__86ab13_idx'),
        ),
    ]
