# Generated by Django 5.2.13 on 2026-04-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('url', models.URLField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor número = primero')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
