# Generated by Django 5.2.13 on 2026-04-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Title')),
                ('categoria', models.CharField(choices=[('viaje', 'Travel'), ('hospedaje', 'Lodging'), ('uniformes', 'Uniforms'), ('equipo', 'Equipment'), ('alimentacion', 'Food & Meals'), ('marketing', 'Marketing'), ('sede', 'Venue'), ('personal', 'Personnel'), ('administrativo', 'Administrative'), ('otro', 'Other')], default='otro', max_length=20, verbose_name='Category')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('MXN', 'MXN')], default='USD', max_length=3, verbose_name='Currency')),
                ('fecha', models.DateField(verbose_name='Date')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Cash'), ('tarjeta', 'Card'), ('transferencia', 'Transfer'), ('otro', 'Other')], max_length=20, verbose_name='Payment method')),
                ('estado', models.CharField(choices=[('pendiente', 'Pending'), ('pagado', 'Paid'), ('cancelado', 'Cancelled')], default='pendiente', max_length=20, verbose_name='Status')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/comprobantes/', verbose_name='Receipt')),
                ('notas', models.TextField(blank=True, verbose_name='Notes')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
