# Generated by Django 5.2.12 on 2026-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.PositiveSmallIntegerField()),
                ('nacionalidad', models.CharField(choices=[('MEX', 'Mexicano'), ('USA', 'Estadounidense'), ('DOM', 'Dominicano'), ('CUB', 'Cubano'), ('VEN', 'Venezolano'), ('PAN', 'Panameño'), ('PRI', 'Puertorriqueño'), ('COL', 'Colombiano'), ('NIC', 'Nicaragüense'), ('CRC', 'Costarricense'), ('GUA', 'Guatemalteco'), ('HON', 'Hondureño'), ('ARG', 'Argentino'), ('BRA', 'Brasileño'), ('OTR', 'Otra')], max_length=3)),
                ('doble_nacionalidad', models.BooleanField(default=False)),
                ('segunda_nacionalidad', models.CharField(blank=True, choices=[('MEX', 'Mexicano'), ('USA', 'Estadounidense'), ('DOM', 'Dominicano'), ('CUB', 'Cubano'), ('VEN', 'Venezolano'), ('PAN', 'Panameño'), ('PRI', 'Puertorriqueño'), ('COL', 'Colombiano'), ('NIC', 'Nicaragüense'), ('CRC', 'Costarricense'), ('GUA', 'Guatemalteco'), ('HON', 'Hondureño'), ('ARG', 'Argentino'), ('BRA', 'Brasileño'), ('OTR', 'Otra')], max_length=3, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
