# Generated by Django 5.2.12 on 2026-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['apellidos', 'nombre'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AddField(
            model_name='jugador',
            name='ciudad_estado',
            field=models.CharField(blank=True, max_length=150, verbose_name='City and State'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipo_ciudad_estado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Team city and state'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipo_viaje',
            field=models.CharField(blank=True, max_length=150, verbose_name='Travel team name'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='es_pitcher',
            field=models.BooleanField(default=False, verbose_name='Pitcher?'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, verbose_name='Instagram handle'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion_principal',
            field=models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('OF', 'Outfield'), ('DH', 'Designated Hitter'), ('UTIL', 'Utility')], max_length=4, verbose_name='Primary position'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion_secundaria',
            field=models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('OF', 'Outfield'), ('DH', 'Designated Hitter'), ('UTIL', 'Utility')], max_length=4, verbose_name='Secondary position'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tutor_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guardian last name'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tutor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Guardian email'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tutor_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guardian first name'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tutor_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Guardian phone'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Last names'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='doble_nacionalidad',
            field=models.BooleanField(default=False, verbose_name='Dual nationality'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nacionalidad',
            field=models.CharField(choices=[('MEX', 'Mexican'), ('USA', 'American'), ('DOM', 'Dominican'), ('CUB', 'Cuban'), ('VEN', 'Venezuelan'), ('PAN', 'Panamanian'), ('PRI', 'Puerto Rican'), ('COL', 'Colombian'), ('NIC', 'Nicaraguan'), ('CRC', 'Costa Rican'), ('GUA', 'Guatemalan'), ('HON', 'Honduran'), ('ARG', 'Argentine'), ('BRA', 'Brazilian'), ('OTR', 'Other')], max_length=3, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='segunda_nacionalidad',
            field=models.CharField(blank=True, choices=[('MEX', 'Mexican'), ('USA', 'American'), ('DOM', 'Dominican'), ('CUB', 'Cuban'), ('VEN', 'Venezuelan'), ('PAN', 'Panamanian'), ('PRI', 'Puerto Rican'), ('COL', 'Colombian'), ('NIC', 'Nicaraguan'), ('CRC', 'Costa Rican'), ('GUA', 'Guatemalan'), ('HON', 'Honduran'), ('ARG', 'Argentine'), ('BRA', 'Brazilian'), ('OTR', 'Other')], max_length=3, null=True, verbose_name='Second nationality'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
    ]
