# Generated by Django 5.2.12 on 2026-04-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_alter_jugador_options_jugador_ciudad_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nacionalidad',
            field=models.CharField(choices=[('AIA', 'Anguilla'), ('ATG', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ABW', 'Aruba'), ('BRB', 'Barbados'), ('BLZ', 'Belize'), ('BMU', 'Bermuda'), ('BOL', 'Bolivia'), ('BES', 'Bonaire, Sint Eustatius and Saba'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('CYM', 'Cayman Islands'), ('CHL', 'Chile'), ('COL', 'Colombia'), ('CRI', 'Costa Rica'), ('CUB', 'Cuba'), ('CUW', 'Curaçao'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('ECU', 'Ecuador'), ('SLV', 'El Salvador'), ('FLK', 'Falkland Islands'), ('GUF', 'French Guiana'), ('GRL', 'Greenland'), ('GRD', 'Grenada'), ('GLP', 'Guadeloupe'), ('GTM', 'Guatemala'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('JAM', 'Jamaica'), ('MTQ', 'Martinique'), ('MEX', 'Mexico'), ('MSR', 'Montserrat'), ('NIC', 'Nicaragua'), ('PAN', 'Panama'), ('PRY', 'Paraguay'), ('PER', 'Peru'), ('PRI', 'Puerto Rico'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('SPM', 'Saint Pierre and Miquelon'), ('VCT', 'Saint Vincent and the Grenadines'), ('BLM', 'Saint-Barthelemy'), ('MAF', 'Saint-Martin (French part)'), ('SXM', 'Sint Maarten (Dutch part)'), ('SGS', 'South Georgia'), ('SUR', 'Suriname'), ('BHS', 'The Bahamas'), ('TTO', 'Trinidad and Tobago'), ('TCA', 'Turks and Caicos Islands'), ('USA', 'United States'), ('UMI', 'United States Minor Outlying Islands'), ('URY', 'Uruguay'), ('VEN', 'Venezuela'), ('VGB', 'Virgin Islands (British)'), ('VIR', 'Virgin Islands (US)'), ('OTR', 'Other')], max_length=3, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='segunda_nacionalidad',
            field=models.CharField(blank=True, choices=[('AIA', 'Anguilla'), ('ATG', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ABW', 'Aruba'), ('BRB', 'Barbados'), ('BLZ', 'Belize'), ('BMU', 'Bermuda'), ('BOL', 'Bolivia'), ('BES', 'Bonaire, Sint Eustatius and Saba'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('CYM', 'Cayman Islands'), ('CHL', 'Chile'), ('COL', 'Colombia'), ('CRI', 'Costa Rica'), ('CUB', 'Cuba'), ('CUW', 'Curaçao'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('ECU', 'Ecuador'), ('SLV', 'El Salvador'), ('FLK', 'Falkland Islands'), ('GUF', 'French Guiana'), ('GRL', 'Greenland'), ('GRD', 'Grenada'), ('GLP', 'Guadeloupe'), ('GTM', 'Guatemala'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('JAM', 'Jamaica'), ('MTQ', 'Martinique'), ('MEX', 'Mexico'), ('MSR', 'Montserrat'), ('NIC', 'Nicaragua'), ('PAN', 'Panama'), ('PRY', 'Paraguay'), ('PER', 'Peru'), ('PRI', 'Puerto Rico'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('SPM', 'Saint Pierre and Miquelon'), ('VCT', 'Saint Vincent and the Grenadines'), ('BLM', 'Saint-Barthelemy'), ('MAF', 'Saint-Martin (French part)'), ('SXM', 'Sint Maarten (Dutch part)'), ('SGS', 'South Georgia'), ('SUR', 'Suriname'), ('BHS', 'The Bahamas'), ('TTO', 'Trinidad and Tobago'), ('TCA', 'Turks and Caicos Islands'), ('USA', 'United States'), ('UMI', 'United States Minor Outlying Islands'), ('URY', 'Uruguay'), ('VEN', 'Venezuela'), ('VGB', 'Virgin Islands (British)'), ('VIR', 'Virgin Islands (US)'), ('OTR', 'Other')], max_length=3, null=True, verbose_name='Second nationality'),
        ),
    ]
