# Generated by Django 5.2.12 on 2026-04-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_americas_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='ciudad_estado',
        ),
        migrations.AddField(
            model_name='jugador',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='estado',
            field=models.CharField(blank=True, max_length=100, verbose_name='State / Province'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='pais',
            field=models.CharField(blank=True, choices=[('USA', 'United States'), ('MEX', 'Mexico'), ('DOM', 'Dominican Republic'), ('CUB', 'Cuba'), ('VEN', 'Venezuela'), ('PRI', 'Puerto Rico'), ('PAN', 'Panama'), ('COL', 'Colombia'), ('NIC', 'Nicaragua'), ('HND', 'Honduras'), ('GTM', 'Guatemala'), ('SLV', 'El Salvador'), ('CRI', 'Costa Rica'), ('ARG', 'Argentina'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('ECU', 'Ecuador'), ('PER', 'Peru'), ('CHL', 'Chile'), ('BOL', 'Bolivia'), ('URY', 'Uruguay'), ('PRY', 'Paraguay'), ('JAM', 'Jamaica'), ('HTI', 'Haiti'), ('TTO', 'Trinidad and Tobago'), ('AIA', 'Anguilla'), ('ATG', 'Antigua and Barbuda'), ('ABW', 'Aruba'), ('BRB', 'Barbados'), ('BLZ', 'Belize'), ('BMU', 'Bermuda'), ('BES', 'Bonaire, Sint Eustatius and Saba'), ('CYM', 'Cayman Islands'), ('CUW', 'Curaçao'), ('DMA', 'Dominica'), ('FLK', 'Falkland Islands'), ('GUF', 'French Guiana'), ('GRL', 'Greenland'), ('GRD', 'Grenada'), ('GLP', 'Guadeloupe'), ('GUY', 'Guyana'), ('MTQ', 'Martinique'), ('MSR', 'Montserrat'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('SPM', 'Saint Pierre and Miquelon'), ('VCT', 'Saint Vincent and the Grenadines'), ('BLM', 'Saint-Barthelemy'), ('MAF', 'Saint-Martin (French part)'), ('SXM', 'Sint Maarten (Dutch part)'), ('SGS', 'South Georgia'), ('SUR', 'Suriname'), ('BHS', 'The Bahamas'), ('TCA', 'Turks and Caicos Islands'), ('UMI', 'United States Minor Outlying Islands'), ('VGB', 'Virgin Islands (British)'), ('VIR', 'Virgin Islands (US)'), ('OTR', 'Other')], max_length=3, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nacionalidad',
            field=models.CharField(choices=[('USA', 'United States'), ('MEX', 'Mexico'), ('DOM', 'Dominican Republic'), ('CUB', 'Cuba'), ('VEN', 'Venezuela'), ('PRI', 'Puerto Rico'), ('PAN', 'Panama'), ('COL', 'Colombia'), ('NIC', 'Nicaragua'), ('HND', 'Honduras'), ('GTM', 'Guatemala'), ('SLV', 'El Salvador'), ('CRI', 'Costa Rica'), ('ARG', 'Argentina'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('ECU', 'Ecuador'), ('PER', 'Peru'), ('CHL', 'Chile'), ('BOL', 'Bolivia'), ('URY', 'Uruguay'), ('PRY', 'Paraguay'), ('JAM', 'Jamaica'), ('HTI', 'Haiti'), ('TTO', 'Trinidad and Tobago'), ('AIA', 'Anguilla'), ('ATG', 'Antigua and Barbuda'), ('ABW', 'Aruba'), ('BRB', 'Barbados'), ('BLZ', 'Belize'), ('BMU', 'Bermuda'), ('BES', 'Bonaire, Sint Eustatius and Saba'), ('CYM', 'Cayman Islands'), ('CUW', 'Curaçao'), ('DMA', 'Dominica'), ('FLK', 'Falkland Islands'), ('GUF', 'French Guiana'), ('GRL', 'Greenland'), ('GRD', 'Grenada'), ('GLP', 'Guadeloupe'), ('GUY', 'Guyana'), ('MTQ', 'Martinique'), ('MSR', 'Montserrat'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('SPM', 'Saint Pierre and Miquelon'), ('VCT', 'Saint Vincent and the Grenadines'), ('BLM', 'Saint-Barthelemy'), ('MAF', 'Saint-Martin (French part)'), ('SXM', 'Sint Maarten (Dutch part)'), ('SGS', 'South Georgia'), ('SUR', 'Suriname'), ('BHS', 'The Bahamas'), ('TCA', 'Turks and Caicos Islands'), ('UMI', 'United States Minor Outlying Islands'), ('VGB', 'Virgin Islands (British)'), ('VIR', 'Virgin Islands (US)'), ('OTR', 'Other')], max_length=3, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='segunda_nacionalidad',
            field=models.CharField(blank=True, choices=[('USA', 'United States'), ('MEX', 'Mexico'), ('DOM', 'Dominican Republic'), ('CUB', 'Cuba'), ('VEN', 'Venezuela'), ('PRI', 'Puerto Rico'), ('PAN', 'Panama'), ('COL', 'Colombia'), ('NIC', 'Nicaragua'), ('HND', 'Honduras'), ('GTM', 'Guatemala'), ('SLV', 'El Salvador'), ('CRI', 'Costa Rica'), ('ARG', 'Argentina'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('ECU', 'Ecuador'), ('PER', 'Peru'), ('CHL', 'Chile'), ('BOL', 'Bolivia'), ('URY', 'Uruguay'), ('PRY', 'Paraguay'), ('JAM', 'Jamaica'), ('HTI', 'Haiti'), ('TTO', 'Trinidad and Tobago'), ('AIA', 'Anguilla'), ('ATG', 'Antigua and Barbuda'), ('ABW', 'Aruba'), ('BRB', 'Barbados'), ('BLZ', 'Belize'), ('BMU', 'Bermuda'), ('BES', 'Bonaire, Sint Eustatius and Saba'), ('CYM', 'Cayman Islands'), ('CUW', 'Curaçao'), ('DMA', 'Dominica'), ('FLK', 'Falkland Islands'), ('GUF', 'French Guiana'), ('GRL', 'Greenland'), ('GRD', 'Grenada'), ('GLP', 'Guadeloupe'), ('GUY', 'Guyana'), ('MTQ', 'Martinique'), ('MSR', 'Montserrat'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('SPM', 'Saint Pierre and Miquelon'), ('VCT', 'Saint Vincent and the Grenadines'), ('BLM', 'Saint-Barthelemy'), ('MAF', 'Saint-Martin (French part)'), ('SXM', 'Sint Maarten (Dutch part)'), ('SGS', 'South Georgia'), ('SUR', 'Suriname'), ('BHS', 'The Bahamas'), ('TCA', 'Turks and Caicos Islands'), ('UMI', 'United States Minor Outlying Islands'), ('VGB', 'Virgin Islands (British)'), ('VIR', 'Virgin Islands (US)'), ('OTR', 'Other')], max_length=3, null=True, verbose_name='Second nationality'),
        ),
    ]
