# Generated by Django 5.2.13 on 2026-04-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0008_reload_locations_comprehensive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='pais',
            name='orden',
            field=models.PositiveSmallIntegerField(default=999, help_text='Lower number = shown first (baseball relevance)'),
        ),
    ]
